apiVersion: v1
kind: Service
metadata:
  name: kafka-booking
  labels:
    app: kafka-booking
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka-booking
  type: ClusterIP