apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: booking-service
spec:
  hosts:
  - booking-service
  http:
    - route:
      - destination:
          host: booking-service
          subset: v1
        weight: 90
      - destination:
          host: booking-service
          subset: v2
        weight: 10
      timeout: 2s
      retries:
        attempts: 2
        perTryTimeout: 1s
        retryOn: 5xx,connect-failure,gateway-error