replicaCount: 3

image:
  name: booking-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8082
  healthCheckPort: 8082

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "production"
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENABLE_FEATURE_X
    value: "true"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info"
  - name: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://booking-service-db:5432/booking
  - name: SPRING_DATASOURCE_USERNAME
    value: booking
  - name: SPRING_DATASOURCE_PASSWORD
    value: booking
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: kafka-booking:9092

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"

livenessProbe:

readinessProbe:

